apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: chainguard-policy
spec:
  images:
  - glob: "ghcr.io/afoteas/**"
  authorities:
  - keyless:
      identities:
      - issuer: "*"
        subject: "*"
