apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod-1
spec:
  priorityClassName: low-priority
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "1100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod-2
spec:
  priorityClassName: low-priority
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "1100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod-3
spec:
  priorityClassName: low-priority
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "1100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod-4
spec:
  priorityClassName: low-priority
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "1100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod-5
spec:
  priorityClassName: low-priority
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "1100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod-6
spec:
  priorityClassName: low-priority
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "1100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod-7
spec:
  priorityClassName: low-priority
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "1100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod-8
spec:
  priorityClassName: low-priority
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "1100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod-9
spec:
  priorityClassName: low-priority
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "1100m"
        memory: "128Mi"
