apiVersion: v1
kind: Pod
metadata:
  name: downwardapi-demo
  labels:
    app: downwardapi-demo
spec:
  containers:
    - name: main
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: labels
            fieldRef:
              fieldPath: metadata.labels
