apiVersion: v1
kind: Pod
metadata:
  name: tolerating-test
spec:
  containers:
  - name: finance-app-container
    image: busybox
    command: [ "sh", "-c", "echo The finance app is running... && sleep 3600" ]
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "finance"
    effect: "NoSchedule"