apiVersion: v1
kind: Pod
metadata:
  labels:
    run: debug
  name: debug
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    name: debug
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
