apiVersion: v1
kind: ConfigMap
metadata:
  name: app-live-config
  labels:
    app: reloader-demo
data:
  # Initial application version
  app.version: "1.0.0" 
  
  # A simple setting
  log.level: "INFO" 
