apiVersion: v1
kind: Pod
metadata:
  labels:
    run: limited
  name: limited
  namespace: ckad-config
spec:
  containers:
  - image: nginx:1.25
    name: limited
    resources:
      limits:
        cpu: 250m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
