apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  labels:
    app: emptydir-demo
spec:
  containers:
  - name: app
    image: busybox:latest
    command: ["/bin/sh", "-c"]
    args:
    - |
      echo "hello from emptyDir test 2" > /cache/msg.txt
      echo "wrote /cache/msg.txt"
      sleep 3600
    volumeMounts:
    - name: cache-vol
      mountPath: /cache
  volumes:
  - name: cache-vol
    emptyDir: {}
