apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: busybox
              args: ["/bin/sh", "-c", "echo Backup complete"]
          restartPolicy: OnFailure
