apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# 1. Reference the base configuration
resources:
- ../../base
commonLabels:
  env: dev
patches:
- target:
    kind: Deployment
    name: web-app
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1