apiVersion: v1
kind: Pod
metadata:
  name: affinity-preferred-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 80
          preference:
            matchExpressions:
              - key: performance
                operator: In
                values:
                  - high
        
        - weight: 20
          preference:
            matchExpressions:
              - key: disktype
                operator: In
                values:
                  - ssd
