apiVersion: v1
kind: Pod
metadata:
  name: affinity-required-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: performance
                operator: In
                values:
                  - high
