apiVersion: v1
kind: ConfigMap
metadata:
  name: app-settings
  labels:
    app: config-demo
data:
  # 1. Key for Method A (Environment Variable Injection)
  log_level: "INFO"
  
  # 2. Key for Method B (Mounted File Injection)
  # Kubernetes will create a file named 'app_config.properties' with this content.
  app_config.properties: |
    # Application Configuration File
    database.host=db-production-01.local
    database.port=5432
    max.connections=50
    feature.flag.beta=true
