apiVersion: v1
kind: Secret
metadata:
  name: azure-queue-auth
type: Opaque
data:
  # Key used by the ScaledJob trigger below
  # Replace this with the base64-encoded Azure Storage Connection String
  STORAGE_CONNECTIONSTRING: <YOUR_BASE64_CONNECTION_STRING> 