apiVersion: v1
kind: Pod
metadata:
  name: hardened-nginx
  annotations:
    container.apparmor.security.beta.kubernetes.io/nginx: localhost/nginx-default
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: nginx
    image: nginx:1.25
