apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual          # must match PV storageClassName
  resources:
    requests:
      storage: 2Gi
