apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv-1
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/k8s-static-pv-demo
    type: DirectoryOrCreate
